local M = {}

local convert_table = {}
local x80 = string.char(0x80)
local x80_y = string.char(0x80, 0xfd)
convert_table[' '] = '<Space>'
convert_table[string.char(01)] = '<C-a>'
convert_table[string.char(02)] = '<C-b>'
convert_table[string.char(03)] = '<C-c>'
convert_table[string.char(04)] = '<C-d>'
convert_table[string.char(05)] = '<C-e>'
convert_table[string.char(06)] = '<C-f>'
convert_table[string.char(07)] = '<C-g>'
convert_table[string.char(08)] = '<C-h>'
convert_table[string.char(09)] = '<Tab>'
convert_table[string.char(10)] = '<C-j>'
convert_table[string.char(11)] = '<C-k>'
convert_table[string.char(12)] = '<C-l>'
convert_table[string.char(13)] = '<CR>'
convert_table[string.char(14)] = '<C-n>'
convert_table[string.char(15)] = '<C-o>'
convert_table[string.char(16)] = '<C-p>'
convert_table[string.char(17)] = '<C-q>'
convert_table[string.char(18)] = '<C-r>'
convert_table[string.char(19)] = '<C-s>'
convert_table[string.char(20)] = '<C-t>'
convert_table[string.char(21)] = '<C-u>'
convert_table[string.char(22)] = '<C-v>'
convert_table[string.char(23)] = '<C-w>'
convert_table[string.char(24)] = '<C-x>'
convert_table[string.char(25)] = '<C-y>'
convert_table[string.char(26)] = '<C-z>'
convert_table[string.char(27)] = '<Esc>'
convert_table[string.char(28)] = '<C-\\>'
convert_table[string.char(29)] = '<C-]>'
convert_table[string.char(31)] = '<C-_>'
convert_table[x80 .. 'kb'] = '<BS>'
convert_table[x80 .. 'ku'] = '↑'
convert_table[x80 .. 'kd'] = '↓'
convert_table[x80 .. 'kl'] = '←'
convert_table[x80 .. 'kr'] = '→'
convert_table[x80 .. 'kh'] = '<Home>'
convert_table[x80 .. '@7'] = '<End>'
convert_table[x80 .. 'kP'] = '<PageUp>'
convert_table[x80 .. 'kN'] = '<PageDown>'
convert_table[x80 .. 'k1'] = '<F1>'
convert_table[x80 .. 'k2'] = '<F2>'
convert_table[x80 .. 'k3'] = '<F3>'
convert_table[x80 .. 'k4'] = '<F4>'
convert_table[x80 .. 'k5'] = '<F5>'
convert_table[x80 .. 'k6'] = '<F6>'
convert_table[x80 .. 'k7'] = '<F7>'
convert_table[x80 .. 'k8'] = '<F8>'
convert_table[x80 .. 'k9'] = '<F9>'
convert_table[x80 .. 'k;'] = '<F10>'
convert_table[x80 .. 'F1'] = '<F11>'
convert_table[x80 .. 'F2'] = '<F12>'
convert_table[x80_y .. string.char(06)] = '<S-F1>'
convert_table[x80_y .. string.char(07)] = '<S-F2>'
convert_table[x80_y .. string.char(08)] = '<S-F3>'
convert_table[x80_y .. string.char(09)] = '<S-F4>'
convert_table[x80_y .. string.char(0)] = '<S-F5>'
convert_table[x80_y .. string.char(11)] = '<S-F6>'
convert_table[x80_y .. string.char(12)] = '<S-F7>'
convert_table[x80_y .. string.char(13)] = '<S-F8>'
convert_table[x80_y .. string.char(14)] = '<S-F9>'
convert_table[x80_y .. string.char(15)] = '<S-F10>'
convert_table[x80_y .. string.char(16)] = '<S-F11>'
convert_table[x80_y .. string.char(17)] = '<S-F12>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'k1'] = '<C-F1>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'k2'] = '<C-F2>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'k3'] = '<C-F3>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'k4'] = '<C-F4>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'k5'] = '<C-F5>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'k6'] = '<C-F6>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'k7'] = '<C-F7>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'k8'] = '<C-F8>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'k9'] = '<C-F9>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'k;'] = '<C-F10>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'F1'] = '<C-F11>'
convert_table[string.char(0x80, 0xfc, 04) .. x80 .. 'F2'] = '<C-F12>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(06)] = '<CS-F1>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(07)] = '<CS-F2>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(08)] = '<CS-F3>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(09)] = '<CS-F4>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(0)] = '<CS-F5>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(11)] = '<CS-F6>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(12)] = '<CS-F7>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(13)] = '<CS-F8>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(14)] = '<CS-F9>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(15)] = '<CS-F10>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(16)] = '<CS-F11>'
convert_table[string.char(0x80, 0xfc, 04) .. x80_y .. string.char(17)] = '<CS-F12>'

local function convert(key)
  if key:len() == 1 and string.byte(key) >= 33 and string.byte(key) <= 126 then
    return key
  end
  return convert_table[key]
end
M.convert = convert

return M
